# Generated by Django 5.2.5 on 2025-08-30 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('country', models.CharField(max_length=50)),
                ('population', models.IntegerField()),
                ('timezone', models.IntegerField()),
                ('sunrise', models.IntegerField()),
                ('sunset', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_main', models.CharField(max_length=50)),
                ('weather_description', models.CharField(max_length=100)),
                ('weather_icon', models.CharField(max_length=10)),
                ('base', models.CharField(max_length=50)),
                ('temp', models.FloatField()),
                ('feels_like', models.FloatField()),
                ('temp_min', models.FloatField()),
                ('temp_max', models.FloatField()),
                ('pressure', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('sea_level', models.IntegerField()),
                ('grnd_level', models.IntegerField()),
                ('visibility', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('wind_deg', models.IntegerField()),
                ('wind_gust', models.FloatField()),
                ('rain_1h', models.FloatField()),
                ('snow_1h', models.FloatField()),
                ('clouds_all', models.IntegerField()),
                ('dt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CurrentWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.location')),
                ('weather', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.weather')),
            ],
        ),
    ]
