# Generated by Django 5.2.5 on 2025-09-29 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('precise_name', models.CharField(blank=True, max_length=150, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('country', models.CharField(max_length=10)),
                ('population', models.IntegerField()),
                ('timezone', models.IntegerField()),
                ('sunrise', models.IntegerField()),
                ('sunset', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_data', models.JSONField(blank=True, default=dict, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('cnt', models.IntegerField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.location')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_weather_data', models.JSONField(blank=True, default=dict, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.location')),
            ],
        ),
    ]
