# Generated by Django 5.2.5 on 2025-09-04 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_location_precise_name_location_precise_population_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='precise_population',
        ),
    ]
