# Generated by Django 5.2.5 on 2025-09-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_location_precise_population'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentweather',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
