# Generated by Django 5.2.5 on 2025-09-11 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_currentweather_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentweather',
            name='weather',
        ),
        migrations.RemoveField(
            model_name='currentweather',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='currentweather',
            name='current_weather_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.location'),
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_data', models.JSONField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.location')),
            ],
        ),
        migrations.DeleteModel(
            name='Weather',
        ),
    ]
