# Generated by Django 5.2.5 on 2025-09-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_currentweather_weather_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentweather',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='forecast',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
