# Generated by Django 5.2.5 on 2025-09-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_location_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='cnt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
